### PR TITLE
Wrote a scan function

### PR DESCRIPTION
**Pull request by 0b1kn00b**
I've got a few other things like materialize, from the Rx codebase, merge, concatenate.

### CODE REVIEW

**Comment by 0b1kn00b** [comment]
It might be worth putting a fold on StreamStep as well, check [Chunk](https://github.com/0b1kn00b/stx_addendum/blob/master/src/main/haxe/stx/Chunk.hx), it's the same structure.

**Comment by back2dos** [comment]
Is there any particular reason for closing this?

I am interested in general, but I think the implementation could be terser and could be added right to Stream for convenience. As for the rest, feel free to open other issues.

**Comment by 0b1kn00b** [comment]
Well, why didn't you say? I figured you were trying to keep it lean. I'll come back round to it.

**Comment by back2dos** [comment]
I do definitely have a religious inclination towards leanness, but my main reason for keeping it in this case is that I am still figuring out a few things, with a relatively strong focus on performance. I was able to get quite a boost with the recent version, which is really constructed around `forEach`, i.e. `map`, `filter`, `fold` and even [`next`](https://github.com/haxetink/tink_streams/blob/52616f82bc405631c0a96fded8fef948737f88b9/src/tink/streams/Stream.hx#L263) are built on it. The converse of building `forEach` on `next` [still exists](https://github.com/haxetink/tink_streams/blob/52616f82bc405631c0a96fded8fef948737f88b9/src/tink/streams/Stream.hx#L203) though, but that only changes things on the lowest layer.

I am interested in fleshing out the API within reason, but I think this may not be the best time to do it, and I am almost certain that I'm not the best person to do it ;)

**Comment by 0b1kn00b** [comment]
Hmm. Reducers in Elm seem to be T->R->R

**Comment by 0b1kn00b** [comment]
I noticed you put a Maybe implementation in the recent commit, I [published one on haxelib](http://lib.haxe.org/p/stx_maybe/)  a few days ago. It relies only on [stax pointwise](https://github.com/0b1kn00b/stx_pointwise) and [stax tuple](https://github.com/0b1kn00b/stx_tuple) which are rather compact.

**Comment by back2dos** [comment]
Closing this now, because we're destroying everything anyway ^^

**Pull request closed without merging**
